-- Compatibility pointer only.
-- The deployed Supabase RLS policy is canonical in:
--   supabase/migrations/0003_rls.sql
-- Keep provider-specific production migrations in the root supabase/migrations directory.
