function toast(message){const old=document.querySelector('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),2800)}
document.addEventListener('DOMContentLoaded',()=>{
  document.querySelector('[data-ask]')?.addEventListener('click',()=>{document.querySelector('#answer')?.classList.remove('hidden');toast('BET checked this question for qualified experience')});
  document.querySelector('[data-research]')?.addEventListener('click',()=>{document.querySelector('#research-state')?.classList.remove('hidden');toast('BET is checking a targeted set of possible experience holders')});
  document.querySelectorAll('[data-onboarding="skip"]').forEach(el=>el.addEventListener('click',()=>{try{localStorage.setItem('bet_onboarding_status','skipped')}catch{}}));
  const send=document.getElementById('support-send'),input=document.getElementById('support-input'),thread=document.getElementById('support-thread');
  if(send&&input&&thread)send.addEventListener('click',()=>{const q=input.value.trim();if(!q)return;const u=document.createElement('div');u.className='support-msg user';u.textContent=q;thread.appendChild(u);input.value='';const b=document.createElement('div');b.className='support-msg bot';const business=/price|pricing|sales|market|hire|hiring|expand|strategy|revenue|profit|should i|should we/i.test(q);b.innerHTML=business?'<b>BET Support</b><br>That sounds like a business question rather than a technical BET issue. <a href="ask.html">Go to Ask BET →</a>':'<b>BET Support</b><br>BET Support handles product and technical issues only. If it cannot resolve the issue, it can escalate to human support.';thread.appendChild(b);thread.scrollTop=thread.scrollHeight});
});
window.BET_FEATURE_FLAGS=Object.assign({payment_safety_messaging:false},window.BET_FEATURE_FLAGS||{});
document.querySelectorAll('[data-feature]').forEach(el=>{if(window.BET_FEATURE_FLAGS[el.getAttribute('data-feature')]===true)el.hidden=false});
