import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { DbPool } from '../../db/pool.js';
const start=z.object({queryId:z.string().uuid(),participantIds:z.array(z.string().uuid()).min(1).max(10)});
const message=z.object({body:z.string().min(1).max(20000)});
export async function registerConversationRoutes(app:FastifyInstance,pool:DbPool,groupEnabled:boolean){
 app.post('/v1/conversations',async(request,reply)=>{
   const b=start.parse(request.body); const own=await pool.query(`select 1 from ask_queries where id=$1 and member_id=$2 and deleted_at is null`,[b.queryId,request.betAuth.userId]); if(!own.rowCount)return reply.code(403).send({error:'query_access_denied'});
   if(b.participantIds.length>1&&!groupEnabled)return reply.code(403).send({error:'group_discussions_disabled'});
   for(const pid of b.participantIds){const eligible=await pool.query(`select 1 from problem_matches pm join experience_records er on er.id=pm.experience_id where pm.query_id=$1 and pm.status='qualified' and er.member_id=$2 limit 1`,[b.queryId,pid]);if(!eligible.rowCount)return reply.code(403).send({error:'participant_not_in_match_pool',participantId:pid});}
   const client=await pool.connect();try{await client.query('begin');const c=await client.query(`insert into conversations(query_id,type,created_by) values($1,$2,$3) returning id,type,status,created_at`,[b.queryId,b.participantIds.length===1?'one_to_one':'group',request.betAuth.userId]);await client.query(`insert into conversation_participants(conversation_id,member_id,invitation_status,joined_at) values($1,$2,'accepted',now())`,[c.rows[0].id,request.betAuth.userId]);for(const pid of b.participantIds)await client.query(`insert into conversation_participants(conversation_id,member_id,invitation_status) values($1,$2,'invited')`,[c.rows[0].id,pid]);await client.query('commit');return reply.code(201).send({data:c.rows[0]});}catch(e){await client.query('rollback');throw e;}finally{client.release();}
 });
 app.get('/v1/conversations',async(request)=>{const {rows}=await pool.query(`select c.id,c.query_id,c.type,c.status,c.created_at from conversations c join conversation_participants p on p.conversation_id=c.id where p.member_id=$1 and p.invitation_status in('accepted','invited') order by c.created_at desc`,[request.betAuth.userId]);return {data:rows};});
 app.post('/v1/conversations/:id/messages',async(request,reply)=>{const b=message.parse(request.body),id=(request.params as any).id;const p=await pool.query(`select 1 from conversation_participants where conversation_id=$1 and member_id=$2 and invitation_status='accepted'`,[id,request.betAuth.userId]);if(!p.rowCount)return reply.code(403).send({error:'conversation_access_denied'});const {rows}=await pool.query(`insert into messages(conversation_id,sender_member_id,body) values($1,$2,$3) returning id,body,created_at`,[id,request.betAuth.userId,b.body]);return reply.code(201).send({data:rows[0]});});
 app.get('/v1/conversations/:id/messages',async(request,reply)=>{const id=(request.params as any).id;const p=await pool.query(`select 1 from conversation_participants where conversation_id=$1 and member_id=$2 and invitation_status in('accepted','invited')`,[id,request.betAuth.userId]);if(!p.rowCount)return reply.code(403).send({error:'conversation_access_denied'});const {rows}=await pool.query(`select id,sender_member_id,body,created_at from messages where conversation_id=$1 and deleted_at is null order by created_at asc limit 500`,[id]);return {data:rows};});
}
